-- Rename HealthReport.cloudinaryUrl to HealthReport.storagePath.
--
-- The column never held a Cloudinary URL. Nothing could write to it: the only
-- caller was POST /reports/upload, which expected the client to have already
-- uploaded the PDF to Cloudinary and to pass the resulting URL in a JSON body,
-- and no client had any Cloudinary code at all. So the table was created, the
-- route was registered, and nothing ever reached it — the verification screen it
-- was built for could only ever have been empty.
--
-- The name was aspirational. health-service has no Cloudinary SDK and no
-- Cloudinary credentials; the only object storage it holds is the private GCS
-- bucket that medicalDocumentStorage.js already writes every prescription and
-- lab report to. This column now holds a path in THAT bucket, which means:
--
--   - The PDF lands in the same `medical/{userId}/` prefix as every other
--     medical record, so the existing prefix sweep on account deletion
--     (consentService.deleteAllDataService) reclaims the blob with no new
--     erasure code. That sweep was written before this column had a writer.
--   - The OCR step, which needs a URL it can fetch, is handed a short-lived
--     signed URL minted at processing time rather than a permanently public one.
--   - The object name is a random uuid and never the user's filename, on the
--     same reasoning as every other medical blob: prescription filenames carry
--     names and conditions and end up in bucket listings and logs.
--
-- Renamed rather than repurposed because a column called cloudinaryUrl that
-- holds a GCS object path is a trap for the next reader, and the table is empty
-- so there is no data to migrate. IF EXISTS/IF NOT EXISTS on the constraint
-- name guard the case where a database created before this migration somehow
-- already has the new name.
ALTER TABLE "health"."HealthReport"
    RENAME COLUMN "cloudinaryUrl" TO "storagePath";