import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  addUserEnteredItem,
  completeItem,
  deactivateItem,
  getPlanForDate,
  isDueOn,
  regenerateSuggestions,
} from '../services/ledger/ledgerPlanService.js';
import { MAX_ACTIVE_PLAN_ITEMS } from '../services/ledger/constants.js';

const TODAY = '2026-09-28'; // a Monday

function mockPrisma(overrides = {}) {
  return {
    planItem: {
      create: async (a) => ({ id: 1, active: true, autoGenerated: false, ...a.data }),
      count: async () => 0,
      findFirst: async () => null,
      findMany: async () => [],
      update: async (a) => ({ id: a.where.id, ...a.data }),
      updateMany: async () => ({ count: 0 }),
      ...overrides.planItem,
    },
    planItemCompletion: {
      upsert: async (a) => ({ ...a.where.planItemId_localDate, ...a.create }),
      ...overrides.planItemCompletion,
    },
    ...overrides.rest,
  };
}

const TARGETS = { kcal: 2200, proteinG: 130, carbsG: 250, fatG: 70, fibreG: 30, waterMl: 3000, micros: { ironMg: 21 } };

// --- the doctor boundary ---------------------------------------------------

test('a user-entered item is origin user, never doctor', async () => {
  let data;
  const prisma = mockPrisma({ planItem: { create: async (a) => ((data = a.data), { id: 1, ...a.data }) } });
  await addUserEnteredItem(prisma, { userId: 7, title: 'Drink more water' });
  assert.equal(data.origin, 'user');
  assert.equal(data.prescribedBy, null);
  assert.equal(data.autoGenerated, false);
});

test('fromPrescription is the only route to origin doctor, and it keeps the typed text', async () => {
  let data;
  const prisma = mockPrisma({ planItem: { create: async (a) => ((data = a.data), { id: 1, ...a.data }) } });
  await addUserEnteredItem(prisma, {
    userId: 7,
    title: 'Metformin 500mg twice daily',
    fromPrescription: true,
    prescribedBy: 'Dr Rao',
  });
  // The title is the user's own words off their prescription. There is no
  // medicine picker anywhere in this path, because a picker is us suggesting a
  // dose.
  assert.equal(data.origin, 'doctor');
  assert.equal(data.title, 'Metformin 500mg twice daily');
  assert.equal(data.prescribedBy, 'Dr Rao');
});

test('prescription details are ignored unless fromPrescription is set', async () => {
  // A client that posts prescribedBy without the flag gets a plain user item,
  // so nothing can be dressed up as a doctor's instruction.
  let data;
  const prisma = mockPrisma({ planItem: { create: async (a) => ((data = a.data), { id: 1, ...a.data }) } });
  await addUserEnteredItem(prisma, { userId: 7, title: 'Stretch', prescribedBy: 'Dr Fake' });
  assert.equal(data.origin, 'user');
  assert.equal(data.prescribedBy, null);
});

test('regenerating only ever writes origin suggested', async () => {
  const created = [];
  const prisma = mockPrisma({
    planItem: {
      count: async () => 0,
      updateMany: async () => ({ count: 3 }),
      create: async (a) => (created.push(a.data), { id: created.length, ...a.data }),
    },
  });
  await regenerateSuggestions(prisma, { userId: 7, goals: ['build_muscle'], targets: TARGETS });
  assert.ok(created.length > 0);
  for (const item of created) {
    assert.equal(item.origin, 'suggested');
    assert.equal(item.autoGenerated, true);
  }
});

test('regenerate soft-deletes suggested items and never touches user or doctor ones', async () => {
  let where;
  const prisma = mockPrisma({
    planItem: {
      count: async () => 0,
      updateMany: async (a) => ((where = a.where), { count: 3 }),
      create: async (a) => ({ id: 1, ...a.data }),
    },
  });
  await regenerateSuggestions(prisma, { userId: 7, goals: ['lose_fat'], targets: TARGETS });
  // Scoped to origin: 'suggested'. If this ever widened, "regenerate" would
  // delete a doctor's course of tablets, which would make the feature dangerous
  // rather than convenient.
  assert.deepEqual(where.origin, 'suggested');
  assert.equal(where.active, true);
});

// --- the active-item cap ---------------------------------------------------

test('a full plan refuses a new item instead of dropping something silently', async () => {
  const prisma = mockPrisma({ planItem: { count: async () => MAX_ACTIVE_PLAN_ITEMS } });
  await assert.rejects(
    () => addUserEnteredItem(prisma, { userId: 7, title: 'One more thing' }),
    /already has 20 active items/,
  );
});

test("a user's own items do not shrink the room available to suggestions", async () => {
  let created = 0;
  const prisma = mockPrisma({
    planItem: {
      // Two active items, both the user's own.
      count: async (a) => {
        if (a.where.origin === 'suggested') return 0;
        return a.where.origin?.in ? 2 : 2;
      },
      updateMany: async () => ({ count: 0 }),
      create: async (a) => (created += 1, { id: created, ...a.data }),
    },
  });
  const out = await regenerateSuggestions(prisma, { userId: 7, goals: ['build_muscle'], targets: TARGETS });
  // Room is 20 - 2 = 18, not 20 - 2 total, because the suggested items being
  // replaced were already counted in the 2.
  assert.equal(out.room, 18);
  assert.equal(out.kept, 2);
});

test('when there is no room, nothing is created and the drop is reported', async () => {
  const prisma = mockPrisma({
    planItem: {
      count: async () => 25,
      updateMany: async () => ({ count: 0 }),
      create: async () => ({ id: 1 }),
    },
  });
  const out = await regenerateSuggestions(prisma, { userId: 7, goals: ['build_muscle'], targets: TARGETS });
  assert.equal(out.created, 0);
  assert.equal(out.room, 0);
  assert.ok(out.dropped > 0);
});

// --- validation ------------------------------------------------------------

test('an empty title is rejected', async () => {
  const prisma = mockPrisma();
  await assert.rejects(() => addUserEnteredItem(prisma, { userId: 7, title: '   ' }), /needs a title/);
});

test('an unknown kind is rejected', async () => {
  const prisma = mockPrisma();
  await assert.rejects(
    () => addUserEnteredItem(prisma, { userId: 7, title: 'x', kind: 'medicine' }),
    /kind must be one of/,
  );
});

test('an over-long title is rejected rather than truncated silently', async () => {
  const prisma = mockPrisma();
  await assert.rejects(
    () => addUserEnteredItem(prisma, { userId: 7, title: 'x'.repeat(300) }),
    /too long/,
  );
});

test('generating without a target is rejected', async () => {
  const prisma = mockPrisma();
  await assert.rejects(
    () => regenerateSuggestions(prisma, { userId: 7, goals: ['build_muscle'] }),
    /before generating a plan/,
  );
});

// --- schedules -------------------------------------------------------------

test('daily is due every day', () => {
  for (const d of ['2026-09-28', '2026-09-29', '2026-10-04']) {
    assert.equal(isDueOn({ schedule: 'daily' }, d, TODAY), true);
  }
});

test('a bare weekday number is one day a week, not all seven', () => {
  // The bug this guards: a schedule of "7" read as a non-matching string either
  // never fired or fired every day.
  const item = { schedule: '7' };
  assert.equal(isDueOn(item, '2026-10-04', TODAY), true); // Sunday
  assert.equal(isDueOn(item, '2026-09-28', TODAY), false); // Monday
});

test('a weekday list only matches those days', () => {
  const item = { schedule: 'mon,wed,fri' };
  assert.equal(isDueOn(item, '2026-09-28', TODAY), true); // Mon
  assert.equal(isDueOn(item, '2026-09-29', TODAY), false); // Tue
  assert.equal(isDueOn(item, '2026-09-30', TODAY), true); // Wed
});

test('a mixed number and name list works', () => {
  // 1 = Monday, and 'thu' = Thursday. 2026-09-30 is a Wednesday, so the
  // Thursday assertion is the 1st, not the 30th.
  assert.equal(isDueOn({ schedule: '1, thu' }, '2026-09-28', TODAY), true); // Mon
  assert.equal(isDueOn({ schedule: '1, thu' }, '2026-09-30', TODAY), false); // Wed
  assert.equal(isDueOn({ schedule: '1, thu' }, '2026-10-01', TODAY), true); // Thu
});

test('a one-off date is only due on that date', () => {
  const item = { schedule: '2026-10-15' };
  assert.equal(isDueOn(item, '2026-10-15', TODAY), true);
  assert.equal(isDueOn(item, '2026-10-16', TODAY), false);
});

test('alternate days alternate, and are not due before the anchor or in the future', () => {
  const item = { schedule: 'every_other_day', createdAt: `${TODAY}T09:00:00.000Z` };
  assert.equal(isDueOn(item, TODAY, TODAY), true);
  // Yesterday is before the anchor, so there is nothing to alternate from.
  assert.equal(isDueOn(item, '2026-09-27', TODAY), false);
  // A future date has not happened yet, so it is not due - the guard is on
  // `today`, not on the schedule arithmetic.
  assert.equal(isDueOn(item, '2026-09-29', TODAY), false);
  assert.equal(isDueOn(item, '2026-10-05', TODAY), false);
  // Viewed on a later day, the alternation holds: the 30th is two days on.
  assert.equal(isDueOn({ ...item }, '2026-09-30', '2026-09-30'), true);
  assert.equal(isDueOn({ ...item }, '2026-09-29', '2026-09-30'), false);
});

test('a malformed schedule is not due, and does not throw', () => {
  // A corrupt schedule should quietly stop counting, never 500 the day screen.
  assert.equal(isDueOn({ schedule: 'someday' }, TODAY, TODAY), false);
  assert.equal(isDueOn({ schedule: 'mon,notaday' }, TODAY, TODAY), false);
  assert.equal(isDueOn({}, 'not-a-date', TODAY), false);
});

// --- completions -----------------------------------------------------------

test('a manual tick is worth exactly one point', async () => {
  let args;
  const prisma = mockPrisma({
    planItem: { findFirst: async () => ({ id: 5, active: true }) },
    planItemCompletion: { upsert: async (a) => ((args = a), { ...a.create }) },
  });
  await completeItem(prisma, { userId: 7, planItemId: 5, localDate: TODAY });
  assert.equal(args.create.points, 1);
  assert.equal(args.create.how, 'manual');
});

test('a client cannot mint points by asking for more', async () => {
  // Without this, any client could POST points: 999 and top its own score.
  let args;
  const prisma = mockPrisma({
    planItem: { findFirst: async () => ({ id: 5, active: true }) },
    planItemCompletion: { upsert: async (a) => ((args = a), { ...a.create }) },
  });
  await completeItem(prisma, { userId: 7, planItemId: 5, localDate: TODAY, points: 999 });
  assert.equal(args.create.points, 1);
});

test('an auto-satisfied item scores zero, so a workout is not credited twice', async () => {
  let args;
  const prisma = mockPrisma({
    planItem: { findFirst: async () => ({ id: 5, active: true }) },
    planItemCompletion: { upsert: async (a) => ((args = a), { ...a.create }) },
  });
  await completeItem(prisma, { userId: 7, planItemId: 5, localDate: TODAY, how: 'auto', points: 5 });
  assert.equal(args.create.points, 0);
});

test('ticking an item twice is an update, not a second row', async () => {
  let args;
  const prisma = mockPrisma({
    planItem: { findFirst: async () => ({ id: 5, active: true }) },
    planItemCompletion: { upsert: async (a) => ((args = a), { ...a.create }) },
  });
  await completeItem(prisma, { userId: 7, planItemId: 5, localDate: TODAY });
  // Keyed on (planItemId, localDate), so a double tap cannot double count.
  assert.deepEqual(args.where.planItemId_localDate, { planItemId: 5, localDate: TODAY });
});

test("another user's item cannot be ticked", async () => {
  const prisma = mockPrisma({ planItem: { findFirst: async () => null } });
  await assert.rejects(
    () => completeItem(prisma, { userId: 7, planItemId: 5, localDate: TODAY }),
    /No such plan item/,
  );
});

test('an inactive item cannot be ticked', async () => {
  const prisma = mockPrisma({ planItem: { findFirst: async () => ({ id: 3, active: false }) } });
  await assert.rejects(
    () => completeItem(prisma, { userId: 7, planItemId: 5, localDate: TODAY }),
    /not active/,
  );
});

// --- reading the day -------------------------------------------------------

test('only due, active items are returned, with completion state', async () => {
  const prisma = mockPrisma({
    planItem: {
      findMany: async () => [
        { id: 1, kind: 'nutrition', schedule: 'daily', endsOn: null, completions: [{ id: 1 }] },
        { id: 2, kind: 'workout', schedule: 'tue', endsOn: null, completions: [] },
        { id: 3, kind: 'habit', schedule: 'daily', endsOn: '2026-09-01', completions: [] },
      ],
    },
  });
  const out = await getPlanForDate(prisma, { userId: 7, localDate: TODAY, today: TODAY });
  // id 2 is a Tuesday item on a Monday; id 3 ended in the past.
  assert.equal(out.total, 1);
  assert.equal(out.items[0].id, 1);
  assert.equal(out.items[0].completed, true);
});

test('an end date is inclusive, so the last day still counts', async () => {
  // "take the tablets until the 30th" includes the 30th. Using `<` here would
  // silently drop the final day of every course, which is the one day a user
  // most needs to be reminded about and the one they are most likely to notice
  // going missing.
  const prisma = mockPrisma({
    planItem: {
      findMany: async () => [
        { id: 1, kind: 'doctor_medication', schedule: 'daily', endsOn: TODAY, completions: [] },
      ],
    },
  });
  const out = await getPlanForDate(prisma, { userId: 7, localDate: TODAY, today: TODAY });
  assert.equal(out.total, 1, 'the end date itself must still be due');
  assert.equal(out.items[0].id, 1);
});

test('a day past the end date is not due', async () => {
  const prisma = mockPrisma({
    planItem: {
      findMany: async () => [
        { id: 1, kind: 'doctor_medication', schedule: 'daily', endsOn: '2026-09-27', completions: [] },
      ],
    },
  });
  const out = await getPlanForDate(prisma, { userId: 7, localDate: TODAY, today: TODAY });
  assert.equal(out.total, 0);
});

test('a malformed end date does not expire the item forever', async () => {
  // The comparison is a string compare, which is only correct while both sides
  // are 'YYYY-MM-DD'. An unpadded '2026-9-1' sorts below '2026-10-05', so before
  // this was guarded, one badly formatted date made every doctor's item vanish
  // with no error from anywhere. Wrongly keeping an item alive is the cheaper
  // failure than wrongly deleting it, so the bad value is ignored.
  const prisma = mockPrisma({
    planItem: {
      findMany: async () => [
        { id: 1, kind: 'doctor_medication', schedule: 'daily', endsOn: '2026-9-1', completions: [] },
      ],
    },
  });
  const out = await getPlanForDate(prisma, { userId: 7, localDate: TODAY, today: TODAY });
  assert.equal(out.total, 1, 'a bad endsOn must not hide a live item');
});

test('deactivating keeps the row, it does not delete it', async () => {
  // Past days reference these rows through their completions, and a frozen
  // score has to stay explicable.
  const prisma = mockPrisma({
    planItem: { findFirst: async () => ({ id: 3, active: true }) },
    update: async (a) => ({ id: 3, ...a.data }),
  });
  const out = await deactivateItem(prisma, { userId: 7, planItemId: 3 });
  assert.equal(out.active, false);
});
