// The plan-item kind allow-list must be the database enum, exactly.
//
// This test exists because the list was wrong in both directions at the same
// time, and both halves of the mistake were invisible:
//
//   - It rejected the four doctor and rest kinds, so every selection the
//     client's dropdown offers came back 400 and the whole doctor scoring path
//     was unreachable from the UI.
//   - It admitted 'appointment' and 'custom', which are not in the enum, so
//     those passed validation and then crashed inside Prisma as a 500.
//
// The second failure is the reason this reads the migration rather than
// restating the list. A test comparing the code against another hand-kept copy
// of the same list passes happily while both copies are wrong. This one reads
// the SQL that created the enum, so it can only pass if the code matches what
// the database will actually accept.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PLAN_ITEM_KINDS, addUserEnteredItem } from '../services/ledger/ledgerPlanService.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const MIGRATION = join(
  HERE,
  '..',
  'prisma',
  'migrations',
  '20260927000000_add_health_ledger',
  'migration.sql',
);

/** The enum values exactly as the migration created them. */
function enumValuesFromMigration() {
  const sql = readFileSync(MIGRATION, 'utf8');
  const match = sql.match(
    /CREATE TYPE "health"\."PlanItemKind" AS ENUM \(([^)]*)\)/,
  );
  assert.ok(match, 'the PlanItemKind enum was not found in the migration');
  return match[1]
    .split(',')
    .map((v) => v.trim().replace(/^'|'$/g, ''))
    .filter(Boolean);
}

function mockPrisma() {
  return {
    planItem: {
      count: async () => 0,
      create: async (a) => ({ id: 1, active: true, autoGenerated: false, ...a.data }),
    },
  };
}

test('the allow-list is the database enum, with nothing added and nothing missing', () => {
  const fromDb = enumValuesFromMigration();

  assert.deepEqual(
    [...PLAN_ITEM_KINDS].sort(),
    [...fromDb].sort(),
    'PLAN_ITEM_KINDS has drifted from health.PlanItemKind. A kind it admits but ' +
      'the database does not will fail inside Prisma as a 500 rather than the ' +
      '400 the caller expects, and a kind it omits is unreachable from the app.',
  );
});

test('no value in the allow-list is absent from the enum', () => {
  // The failure mode this guards is specifically "valid here, invalid in the
  // database", because that one is a crash rather than a rejection and the
  // difference is invisible until a user taps the exact right button.
  const fromDb = new Set(enumValuesFromMigration());
  const orphans = PLAN_ITEM_KINDS.filter((k) => !fromDb.has(k));
  assert.deepEqual(orphans, [], 'these kinds would pass validation then 500 in Prisma');
});

test('every kind the client offers is accepted', async () => {
  // The client's dropdown iterates PlanItemKind.values, which is the same seven
  // values. Each one has to survive the round trip or a user tapping it in the
  // dialog gets an error.
  const prisma = mockPrisma();
  for (const kind of PLAN_ITEM_KINDS) {
    const out = await addUserEnteredItem(prisma, {
      userId: 7,
      title: `a ${kind} item`,
      kind,
    });
    assert.equal(out.kind, kind);
  }
});

test('the doctor kinds are accepted, which is what makes them reachable', async () => {
  // Named individually because these are the four the bug actually locked out,
  // and a reader should not have to diff two lists to see that.
  const prisma = mockPrisma();
  for (const kind of ['doctor_medication', 'doctor_test', 'doctor_appointment', 'rest']) {
    const out = await addUserEnteredItem(prisma, {
      userId: 7,
      title: 'Metformin 500mg',
      kind,
      fromPrescription: true,
      prescribedBy: 'Dr Rao',
    });
    assert.equal(out.kind, kind);
    assert.equal(out.origin, 'doctor');
    assert.equal(out.prescribedBy, 'Dr Rao');
  }
});

test('an unknown kind is still rejected with a 400', async () => {
  await assert.rejects(
    () => addUserEnteredItem(mockPrisma(), { userId: 7, title: 'x', kind: 'medicine' }),
    /kind must be one of/,
  );
});

test('the retired custom kind is rejected rather than crashing in Prisma', async () => {
  // 'custom' used to be allow-listed and did not exist in the enum.
  await assert.rejects(
    () => addUserEnteredItem(mockPrisma(), { userId: 7, title: 'x', kind: 'custom' }),
    /kind must be one of/,
  );
});